### ISSUE TITLE
UI mess in M51

### ISSUE THREAD

**Issue by mnf1980** [muchimi/JoystickGremlinEx#247]
I have multiple UI issues with M51
as you see in the pic, it is not readable anymore.
I remember there were Mode and Setting tabs; I don't know if it is removed or not visible in this build.

![image](https://github.com/user-attachments/assets/63257bd9-4db4-428d-9765-e6560ac0dc03)

**Comment by mnf1980** [comment]
While investigating the problem, I discovered a faulty profile caused the UI mess. 

The issue occurred when I attempted to add a second profile Mode, which resulted in an error (which I couldn't reproduce). The UI mess happened after I closed and reopened JGEx; I could not load my profile after that, and the profile was dead.

Surprisingly, upon further inspection, I found a folder named "m51" inside my profiles directory. This folder contained two files with the same name as my original file but appended with ".1" and ".2." These appear to be backups of my original profile, as they matched the working profile before I attempted to add the second profile Mode.

Restoring the profiles from the "m51" folder resolved the UI issue, and everything functions correctly.

What is the purpose of the m51? It saved me a month of work!!

**Comment by treydeal** [comment]
There does indeed seem to be something strange happening on m50 and m51 - even when removing the Joystick Gremlin Ex folder in my user directory, the tabs don't seem to function correctly. Some examples:

- One of my joysticks shows up as two devices in all games and in Joystick Gremlin, which is normal, but in m51 the second non-functioning joystick tab has the device name as my rudder pedals.
- My rudder pedals sliders are actually on the tab labeled Keyboard.
- Swapping the tab order does not actually move where the functional sliders are - the functional rudders are always on tab 4 and the phantom 2nd joystick is always on tab 3.
- MIDI looks to be the real Keyboard tab, OSC is MIDI, Mode is OSC, Settings is Plugins, and Plugins also appears to be Plugins - so I have no functional Settings tab at all.
- My rudder pedals also show up as two devices, one of them being a non-functional phantom device much like the above joystick, and this particular device would cause an error when the tab was clicked in an older version of Joystick Gremlin Ex. I was able to find the phantom device in Device Manager and set it to Disabled without any ill effects, which was great b/c it was helping to clean up the input from games too (unfortunately I lose functionality when disabling the phantom joystick, so it has to stay enabled). This is relevant to the topic - if I reenable the phantom rudder pedal device, instead of having the 9 tabs in Joystick Gremlin with their oddities, suddenly I only have 3, and can only access the other devices by having automatic input switching enabled...it doesn't visibly switch the tab at the top, but the sliders/buttons are functional. After that device is enabled, it's impossible to get to the Keyboard/MIDI/Settings/etc. tabs, even though some are not functional at all when being displayed.

I've reverted back to m49b for the time being, as that's the last version with all functional tabs, and the ability to drag the tab order with the devices actually following the tabs.

**Comment by muchimi** [comment]
As documented in the patch notes, there is a new automatic backup mechanism enabled by default for the specific situation when a profile somehow gets corrupted (either via a bug or a manual edit gone sideways).  Whenever a profile is saved, and the option is enabled (see patch notes), a backup of the old profile before modifications will be made on save in a roundrobin manner.  The number of backups kept is an option in the profiles option pages in GremlinEx.

Whenever a problem occurs in GremlinEx, the first thing to do is try a new profile and see if the problem persists.  The second thing to try is to restart GremlinEx without adding or removing devices - just because doing so adds a lot of complexity and makes it more difficult to narrow down the root cause.   While GremlinEx handles older versions and does conversions automatically, there may still be edge cases where that doesn't happen correctly, everyone's hardware is different to boot.

Because of this change, UI may go sideways for a bit as issues and edge cases are reported.

The log file has heavy instrumentation that helps diagnose issues so if you want to send me the problematic profile xml and the log file, that will help identify what the issues may have been.

**Comment by treydeal** [comment]
That all makes perfect sense - I've attached a clean Joystick Gremlin Ex folder from my user directory, where I've launched the application, closed it, relaunched and created a new empty profile, closed and relaunched again. It seems like the above issues stick around through the process.

[Joystick Gremlin Ex.zip](https://github.com/user-attachments/files/18269996/Joystick.Gremlin.Ex.zip)

Thanks for looking into this, and let me know if I can help with more details!

**Comment by muchimi** [comment]
I have identified a few more issues with the tracking of devices to their tabs.  Presently working on this.

**Comment by muchimi** [comment]
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m52.zip

**Comment by treydeal** [comment]
Device tabs appear to be functional again! However, I'm now getting an error popup when I try to go to either the Settings or Plugins tab:

```
ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 565, in _tab_selected
   File "gremlin\config.py", line 1529, in get_last_input
   File "gremlin\config.py", line 1467, in _get_input_id
 AssertionError: Config: GetInputId() Don't know how to handle device type: 0
```
This is using a clean config directory in my user folder, and relaunching before/after creating a new profile - see attached below!

[Joystick Gremlin Ex.zip](https://github.com/user-attachments/files/18271378/Joystick.Gremlin.Ex.zip)
[dill_debug.txt](https://github.com/user-attachments/files/18271379/dill_debug.txt)

**Comment by muchimi** [comment]
Please try m52, which resolves some more challenges with the new device UI on reload and re-order.

**Comment by treydeal** [comment]
> Please try m52, which resolves some more challenges with the new device UI on reload and re-order.

My newest logs above are from m52 - let me know if I should start a new issue thread for the Settings & Plugins tab errors, since they don't seem directly related to the UI visual issues, and at least for me the visual issues I was seeing on some tabs aren't present in m52.

**Comment by muchimi** [comment]
Thank you for confirming the tabs are behaving again in m52. 
The content of the settings/plugins will be resolved in m53.

**Comment by muchimi** [comment]
The issue with the settings/plugins is resolved with m53.  Closing this issue.

**Comment by mnf1980** [comment]
I still have the UI mess in m53.

**Case 1:**
https://github.com/user-attachments/assets/c59d6f3d-027f-437c-829a-68adb6ecd7e9

**Case 2:**
https://github.com/user-attachments/assets/839f9311-80fb-46ae-8261-1d44d31c684a

**Comment by treydeal** [comment]
Ah yeah, fantastic videos - can confirm these UI issues exist at 100% scaling as well.
