### ISSUE TITLE
m66a - Temporary Mode Switch No Longer Works as Expected

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#299]
In previous builds, up to at least m62a, the Temporary Mode Switch function worked without fail.

Basically on a Virpil Alpha Prime Left Button 4 and 5.

STEP 1:  Press and hold 1st stage of trigger (Button 4) and it would call the L-ALT MODE and hold down the LALT Key.
STEP 2:  Press further to 2nd stage of trigger (Button 5) and it would call the R-ALT MODE and hold down the RALT Key.

Let up back to Button 4 and it would return to L-ALT MODE and hold down LALT Key.
Let all the way up and returns to parent FLIGHT MODE.

I'm sending you Profile that worked in m62a but no longer works in m66a.

In m66a, it will only go to the first step (above), but won't go to second step.  So, in effect, Pressing to Button 5 and holding will no longer switch the mode to R-ALT and hold down the RALT Key.

**Comment by muchimi** [comment]
To troubleshoot this further, I added in m67 additional diagnostics code to the temporary mode action to document what it's doing or not, and what events it's getting.

**Comment by ZK-273** [comment]
Still not working in m67c

**Comment by muchimi** [comment]
Can you please share the relevant portions of the log file so we can see the logic in action as to what it's doing?

**Comment by ZK-273** [comment]
@muchimi Further details and logs sent to you in Discord

**Comment by ZK-273** [comment]
Found the issue.

The below following screenshot shows conditions that always reset back to 'PRESSED' and 'USE CALIBRATED INPUT'.

Even if I change the condition to 'RELEASED' and uncheck 'USED CALIBRATED INPUT', Save, the Profile, and reload it.  It always returns as the below screen shot.

In looking at the XML, it seems there's no lines for 'Comparison' (Pressed or Released), nor is there anything being saved in the profile to track the Use Calibrated option either.

![Image](https://github.com/user-attachments/assets/ec35e106-559c-4ab1-a537-f51eb6334ac1)

As the conditions always pop up as 'PRESSED' now and not 'RELEASED', it prevents the mode to continue to switch to the RALT mode.

**Comment by muchimi** [comment]
That was an obscure issue and linked to an "if" statement that should not have been there.  I believe it is resolved in m67d.

**Comment by ZK-273** [comment]
@muchimi Still happens in m67d

The XML doesn't have anything like Comparison = 'PRESSED', nor showing anything about auto-calibrate in the lines in XML for the condition.  Even after saving.

**Comment by ZK-273** [comment]
Confirmed fixed for m67e  Thanks
