### ISSUE TITLE
m68 - Conditional Ranges In Container Not Being Saved/Retained Across Devices

### ISSUE THREAD

**Issue by ZK-273** [muchimi/JoystickGremlinEx#305]
It was found that when putting in a second condition that was either a Vjoy or Joystick Condition, that the ranges on the axis weren't saving.

I tried it with just a single conditional range and that also didn't save.

I did a reset of the container and remade the following conditions.  Placed the range INSIDE 0.001 to 1.000.  Saved Profile.  Navigated away from the device tab, and back to it, and the rangers were cleared to 0.000

![Image](https://github.com/user-attachments/assets/5f9460ce-cbd3-4fd6-b12c-94ba19da4300)

Here is the resulting saved result in the .xml file.  Notice the condition only has the Low and High range as 0.0.  Even though I specified in the application a low of 0.001 and high of 1.000

> <container type="basic" container_id="a7edca70bddc4eda9cc109f715d22bae">
>             <action-set>
>               <macro action_id="28247d7fdd2c456092a59512848121d2">
>                 <properties/>
>                 <actions>
>                   <vjoy vjoy-id="2" input-type="button" input-id="60" value="True"/>
>                 </actions>
>               </macro>
>               <text-to-speech voice_id="0" text="RIGHT LEVER LOCKED" volume="100" rate="80" action_id="ef25367ffa27413b92c2c06054fa09ee"/>
>             </action-set>
>             <virtual-button lower-limit="0.995" upper-limit="1.0" direction="below" enabled="True"/>
>             <activation-condition rule="all" condition_id="df09291dad8d457aac78655e21c93ecb">
>               <condition condition_id="79329ba229684f1fbf7e4ee526c5c56b" comparison="released" condition-type="vjoy" input="button" id="60" vjoy-id="2"/>
>               <condition condition_id="a36a670dd0814f8baf420df807d6d797" comparison="inside" condition-type="vjoy" input="axis" id="7" vjoy-id="1" range-low="0.0" range-high="0.0"/>
>             </activation-condition>
>           </container>

**Comment by Lolo401** [comment]
I can confirm the issue.
A blank profile was created in m68.  A vjoyremap action was mapped to a random button. A condition was setup to only activate the action based on a vjoy 1 axis 1 condition or a AZERON physical axis position.  The values were changed to random values within acceptable range (0.5 and -0.5), as can be seen on image 1.  Another button was selected to cause the UI to switch to another window.  Coming back to the condition window showed all values reverting back to 0.000 and 0.000 on both the VJoy and Joystick condition as can be seen on image 2.

![Image](https://github.com/user-attachments/assets/e78cfdee-f3a4-4673-8dc9-170e625d8c77)
Image 1 - Conditions setup

![Image](https://github.com/user-attachments/assets/b0203741-026f-40c0-9ab9-81339aafdec7)
Image 2 - Conditions after UI refresh by selecting another button

**Comment by muchimi** [comment]
Resolved in:
https://github.com/muchimi/JoystickGremlinEx/releases/download/13.40.16ex_m/joystick_gremlin_13_40_16_m68a.zip

**Comment by ZK-273** [comment]
Still not working

 "Recording 2025-01-23 103801.mp4" -->

**Comment by ZK-273** [comment]
Unfortunately still not working:

https://youtu.be/-8CWVKMP4sk

**Comment by ZK-273** [comment]
Seems to be working now.
