### ISSUE TITLE
m72c - Gated Axis problems

### ISSUE THREAD

**Issue by Prankoys** [muchimi/JoystickGremlinEx#331]
**Version:**
13.40.16ex (m72c)

**Intention:**
Use the Gated Axis action to map an analog stick's axes to keyboard outputs, specifically the up, down, right, and left arrow keys.

**Problem:**
There are two, actually.

1. Setting a Gated Axis action seemingly causes GremlinEx to detect a ghost Button 1 hold input on the hardware device, which is then transmitted to the vJoy device when the profile is active. Sometimes the Input Viewer doesn't even register this ghost input on the hardware, but it reflects in vJoy anyway. Axis movement in the Input Viewer is also noticeably laggy/inaccurate compared to what's seen in the main interface.
2. When opening another profile, Gated Axis mappings don't seem to be cleared, causing them (and sometimes the abovementioned phantom button presses) to persist in another profile without those mappings.

I initially thought this was a sign of hardware failure with my throttle, but then I tried gate mapping on my stick, and the same thing happened.

[Video example with timestamps](https://youtu.be/--eGzUGy-lI)

**Steps to Reproduce:**
I'm unable to pin down the exact sequence that triggers it, but roughly...

1. Add a Gated Axis mapping.
2. Set gates to 4, adjust middle gates (2 and 3) to provide a pseudo-deadzone. Map KeyboardEx actions for upper and lower ranges.
3. Repeat for another axis.
4. Save and activate the profile.
5. The gated axis may work as intended at first, but eventually (I'm not certain what the exact trigger is) GremlinEx will start registering ghost inputs on button 1 (Problem 1).
6. Deactivate the profile, then load and activate a different one with no Gated Axis actions on the same axes.
7. Whatever actions were mapped to the gated axes will still be sent to vJoy despite being on a different profile (Problem 2).

**Comment by muchimi** [comment]
Thank you for reporting.
The ghost button issue is resolved (to my knowledge) in m73, which is currently in testing as it's a work in progress - it occurred because some actions were double triggering the event, which would act as a toggle depending on the action being used.
What I'd recommend is to try m73t and see if it resolved the issue.  There are other fixes in m73 as well, and while it's still in testing - it is as functional as m72, although I may see rapid-fire updates (more than usual!) as I have them.

https://github.com/muchimi/JoystickGremlinEx/releases/download/test/joystick_gremlin_13_40_16_m73t.zip

**Comment by Prankoys** [comment]
Many thanks for the quick response and the link to m73t, I'll be using that build from now until the next release.

Unfortunately the problem persists even in m73t ([Video](https://youtu.be/rVh0OECDGyI)). I also tried deleting config.json and creating a fresh profile with only Gated Axis actions on the two axes I needed to change, just to see whether it'd work without any potential interference from other actions. Same result.

**Comment by muchimi** [comment]
Please try this with

https://github.com/muchimi/JoystickGremlinEx/releases/download/test/joystick_gremlin_13_40_16_m73t2.zip

Gated axis saw number of recent iterations with m73 (at least 5) - one reason there' s a number after t now because we'd forget which iteration it was (meaning, I would forget).

**Comment by Prankoys** [comment]
The link to t2 gives me a file not found error, but I tried with the available test versions on the release page (t1, t6, and t7). Sadly, the problem still occurs in all three.

**Comment by TalorienBR** [comment]
Hi muchimi, GREX is amazing, thanks for your work!

I'm having this issue on m74t6. Adding a gated axis to a certain joystick axis (VKB MCGU brake lever) consistently adds a phantom activation of that joystick's Button 1 whenever brake lever is activated.

**Comment by muchimi** [comment]
Marking this as resolved.  We can reopen if the issue persists in the current test release.
